# Generated by Django 2.2.15 on 2020-10-02 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MrQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=1000, null=True, verbose_name='السؤال:')),
                ('image_question', models.ImageField(blank=True, null=True, upload_to='', verbose_name='اسأل بصوره:')),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_answer', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_mr_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
