# Generated by Django 3.1.1 on 2020-09-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrquestion',
            name='image_answer',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mrquestion',
            name='image_question',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mrquestion',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
