# Generated by Django 2.2.15 on 2020-10-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201008_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrquestion',
            name='image_answer',
            field=models.ImageField(blank=True, null=True, upload_to='images/questions'),
        ),
    ]
