# Generated by Django 2.2.15 on 2020-10-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20201008_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrquestion',
            name='image_question',
            field=models.ImageField(blank=True, null=True, upload_to='images/questions', verbose_name='اسأل بصوره:'),
        ),
    ]
