# Generated by Django 2.2.15 on 2021-07-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20201008_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrQuestionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr_question_file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mr_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mr_question_file', to='questions.MrQuestion')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
