# Generated by Django 2.2.15 on 2020-10-08 23:19

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20201008_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrquestion',
            name='image_question',
            field=s3direct.fields.S3DirectField(blank=True, null=True, verbose_name='اسأل بصوره:'),
        ),
    ]
