# Generated by Django 2.2.15 on 2020-10-09 01:01

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20201009_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrquestion',
            name='image_question',
            field=s3direct.fields.S3DirectField(default='asdas/dasdas'),
            preserve_default=False,
        ),
    ]
