# Generated by Django 2.2.15 on 2020-10-09 01:03

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20201009_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrquestion',
            name='image_question',
            field=s3direct.fields.S3DirectField(blank=True, null=True, verbose_name='اسأل بصوره:'),
        ),
    ]
