# Generated by Django 2.2.15 on 2020-10-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20201009_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrquestion',
            name='image_question',
            field=models.ImageField(blank=True, null=True, upload_to='images/questions', verbose_name='اسأل بصوره:'),
        ),
    ]
