# Generated by Django 2.2.15 on 2020-10-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ('created_at',)},
        ),
    ]
