# Generated by Django 2.2.15 on 2020-09-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='week_day',
            field=models.CharField(choices=[(0, 'السبت'), (1, 'الأحد'), (2, 'الاثنين'), (3, 'الثلاثاء'), (4, 'الاربعاء'), (5, 'الخميس'), (6, 'الجمعة')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
