# Generated by Django 2.2.15 on 2020-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='week_day',
            field=models.IntegerField(blank=True, choices=[(5, 'السبت'), (6, 'الأحد'), (0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الاربعاء'), (3, 'الخميس'), (4, 'الجمعة')], null=True),
        ),
    ]
