# Generated by Django 2.2.15 on 2020-10-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20201007_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('created_at',)},
        ),
    ]
