# Generated by Django 2.2.15 on 2020-09-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200911_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='week_day',
            field=models.IntegerField(blank=True, choices=[(0, 'السبت'), (1, 'الأحد'), (2, 'الاثنين'), (3, 'الثلاثاء'), (4, 'الاربعاء'), (5, 'الخميس'), (6, 'الجمعة')], null=True),
        ),
    ]
