# Generated by Django 3.1.1 on 2020-09-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200902_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parentPhoneNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
