# Generated by Django 3.1.1 on 2020-09-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200903_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='model_pic',
            new_name='profile_pic',
        ),
    ]
