# Generated by Django 2.2.15 on 2020-10-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201010_0720'),
        ('accounts', '0004_auto_20201010_0348'),
    ]

    operations = [
    ]
