# Generated by Django 2.2.15 on 2020-10-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201016_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpayment',
            old_name='available_lectures',
            new_name='number_available_lectures',
        ),
    ]
