# Generated by Django 2.2.15 on 2020-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201016_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='last_lecture_attended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
