# Generated by Django 3.1.1 on 2020-09-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200904_0113'),
        ('accounts', '0008_auto_20200904_0130'),
    ]

    operations = [
    ]
