# Generated by Django 2.2.15 on 2020-12-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_studentpayment_remainder_available_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='examGrade',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='examStudentGrade',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='homeWorkAnswerd',
            field=models.BooleanField(default=False),
        ),
    ]
