# Generated by Django 2.2.15 on 2020-09-11 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='classes.Class'),
        ),
    ]
