# Generated by Django 2.2.15 on 2020-09-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200911_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'student'), (1, 'admin')], default=0),
        ),
    ]
