# Generated by Django 2.2.15 on 2021-09-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201204_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
