# Generated by Django 2.2.15 on 2020-09-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='random_password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='classes.Class', verbose_name='المجموعة'),
        ),
    ]
