# Generated by Django 2.2.15 on 2020-09-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200918_1023'),
        ('accounts', '0010_auto_20200906_1040'),
    ]

    operations = [
    ]
