# Generated by Django 2.2.15 on 2020-09-22 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200922_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='classes.Class', verbose_name='المجموعة'),
        ),
    ]
