# Generated by Django 2.2.15 on 2020-09-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200922_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='classes.Class', verbose_name='المجموعة'),
        ),
    ]
