# Generated by Django 2.2.15 on 2020-10-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_homework_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='homework_text2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الواجب'),
        ),
    ]
