# Generated by Django 2.2.15 on 2020-09-29 15:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_studentexam_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
