# Generated by Django 2.2.15 on 2020-10-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_homework_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='homework_text1',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='homework_text2',
        ),
    ]
