# Generated by Django 2.2.15 on 2020-09-03 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200903_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentchoiceanswer',
            name='student_exam',
        ),
        migrations.RemoveField(
            model_name='studentessayanswer',
            name='student_exam',
        ),
        migrations.RemoveField(
            model_name='studenttruefalseanswer',
            name='student_exam',
        ),
        migrations.DeleteModel(
            name='StudentExam',
        ),
    ]
