# Generated by Django 2.2.15 on 2020-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20200929_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
