# Generated by Django 2.2.15 on 2020-10-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20201004_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
