# Generated by Django 2.2.15 on 2021-07-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201204_2351'),
        ('exams', '0004_auto_20201013_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='student_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture', to='accounts.StudentPayment'),
        ),
    ]
