# Generated by Django 2.2.15 on 2021-07-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_studentexam_student_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='student_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exam', to='accounts.StudentPayment'),
        ),
    ]
