# Generated by Django 2.2.15 on 2020-09-29 18:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20200929_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='questions_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
