# Generated by Django 2.2.15 on 2020-09-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20200903_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_question', to='exams.Exam'),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_question', to='exams.Exam'),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_question', to='exams.Exam'),
        ),
    ]
