# Generated by Django 2.2.15 on 2020-09-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_studentexam_questions_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchoiceanswer',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
