# Generated by Django 2.2.15 on 2020-09-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20200903_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_choice_answer', to='exams.ChoiceQuestion'),
        ),
    ]
