# Generated by Django 2.2.15 on 2020-09-04 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20200904_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentessayanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_essay_answer', to='exams.EssayQuestion'),
        ),
    ]
