# Generated by Django 2.2.15 on 2020-09-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20200904_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentessayanswer',
            name='answer',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
