# Generated by Django 2.2.15 on 2020-10-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20201001_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentessayanswer',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
