# Generated by Django 2.2.15 on 2020-09-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20200904_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_quiz',
            field=models.IntegerField(default=0, help_text='In minutes'),
        ),
    ]
