# Generated by Django 2.2.15 on 2020-10-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20201001_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='been_a_week',
            field=models.BooleanField(default=False),
        ),
    ]
