# Generated by Django 2.2.15 on 2020-09-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_auto_20200905_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchoiceanswer',
            name='grade',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
