# Generated by Django 2.2.15 on 2020-09-11 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_auto_20200907_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentexam',
            old_name='score',
            new_name='grade',
        ),
    ]
