# Generated by Django 2.2.15 on 2020-09-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_auto_20200911_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='score',
            new_name='grade',
        ),
    ]
