# Generated by Django 2.2.15 on 2020-09-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_auto_20200911_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
    ]
