# Generated by Django 2.2.15 on 2020-09-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_auto_20200911_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='availabe_from',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='availabe_to',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='max_tries',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[(0, 'امتحان اختياري'), (1, 'امتحان اختياري ومقالي')], default=0, max_length=1),
        ),
    ]
