# Generated by Django 2.2.15 on 2020-09-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_auto_20200911_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexam',
            name='try_number',
        ),
        migrations.AddField(
            model_name='studentexam',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[(0, 'امتحان اختياري'), (1, 'امتحان اختياري و مقالي')], default=0, max_length=1),
        ),
    ]
