# Generated by Django 2.2.15 on 2020-09-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_auto_20200911_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.IntegerField(choices=[(0, 'امتحان اختياري'), (1, 'امتحان اختياري و مقالي')], default=0),
        ),
    ]
