# Generated by Django 2.2.15 on 2020-09-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_auto_20200911_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
