# Generated by Django 2.2.15 on 2020-09-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20200913_0918'),
        ('exams', '0023_studentexam_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.Week', verbose_name='الحصة'),
        ),
    ]
