# Generated by Django 2.2.15 on 2020-09-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_exam_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.IntegerField(default=0, verbose_name='الوقت بالدقايق'),
        ),
    ]
