# Generated by Django 2.2.15 on 2020-10-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='description1',
        ),
    ]
