# Generated by Django 2.2.15 on 2020-10-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_text1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الواجب'),
        ),
    ]
