# Generated by Django 2.2.15 on 2020-10-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homework_homework_text1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='homework_text1',
        ),
    ]
