# Generated by Django 2.2.15 on 2020-10-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_remove_homework_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='show_answer',
            field=models.BooleanField(default=False),
        ),
    ]
