# Generated by Django 2.2.15 on 2020-10-10 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0004_auto_20201010_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomeworkMakeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homework_makeup', to='homework.Homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homework_makeup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
