# Generated by Django 2.2.15 on 2020-12-05 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_auto_20201106_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='studenthomeworkmakeup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenthomeworkmakeup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
