# Generated by Django 2.2.15 on 2020-09-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlecture',
            name='special_access',
            field=models.BooleanField(default=False),
        ),
    ]
