# Generated by Django 2.2.15 on 2020-10-03 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_studentlecturemakeup_studentseenlecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlecturemakeup',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lecture_makeup', to='lectures.Lecture'),
        ),
        migrations.AlterField(
            model_name='studentlecturemakeup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lecture_makeup', to=settings.AUTH_USER_MODEL),
        ),
    ]
