# Generated by Django 2.2.15 on 2020-09-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_studentlecture_special_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='link',
            field=models.TextField(),
        ),
    ]
