# Generated by Django 2.2.15 on 2020-09-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20200909_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='link',
        ),
        migrations.CreateModel(
            name='LectureLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_link', to='lectures.Lecture')),
            ],
        ),
    ]
