# Generated by Django 2.2.15 on 2020-10-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20201007_0250'),
        ('lectures', '0003_auto_20201004_0127'),
    ]

    operations = [
    ]
