# Generated by Django 2.2.15 on 2020-10-12 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_studentseenlecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='lecturelink',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='studentlecture',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='studentlecturemakeup',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='studentlecturequestion',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='studentseenlecture',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='lecturelink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturelink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentlecturemakeup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlecturemakeup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentseenlecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentseenlecture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
