# Generated by Django 2.2.15 on 2020-10-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_auto_20201013_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='lecturelink',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='studentlecture',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='studentlecturemakeup',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='studentlecturequestion',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='studentseenlecture',
            options={'ordering': ('id',)},
        ),
    ]
