# Generated by Django 2.2.15 on 2020-10-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_auto_20201013_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_manual_allow',
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
