# Generated by Django 2.2.15 on 2020-10-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_auto_20201013_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_manual_allow',
        ),
    ]
