# Generated by Django 2.2.15 on 2020-10-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0008_auto_20201016_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_allowed_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
