# Generated by Django 2.2.15 on 2020-10-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201016_1806'),
        ('lectures', '0009_auto_20201016_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlecture',
            name='student_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_payment', to='accounts.StudentPayment'),
        ),
    ]
