# Generated by Django 2.2.15 on 2020-10-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_studentlecture_student_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlecture',
            name='student_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_lecture', to='accounts.StudentPayment'),
        ),
    ]
