# Generated by Django 2.2.15 on 2020-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0012_auto_20201023_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
