# Generated by Django 2.2.15 on 2020-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0013_lecture_is_permanent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_allowed_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
