# Generated by Django 2.2.15 on 2020-11-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0015_studentlecture_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlecture',
            name='test',
        ),
    ]
