# Generated by Django 2.2.15 on 2020-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0016_remove_studentlecture_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
