# Generated by Django 2.2.15 on 2020-12-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0017_auto_20201205_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlecture',
            name='seen_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentlecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
