# Generated by Django 2.2.15 on 2020-12-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0017_studentlecture_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlecture',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
